# Generated by Django 4.2.2 on 2023-10-18 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_detail_delete_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='f_name',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='l_name',
        ),
    ]
