# Generated by Django 4.2.2 on 2023-10-20 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_detail_f_name_remove_detail_l_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='f_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='detail',
            name='l_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
